###################################################
# Makefile for the DTHomeworks
###################################################

report: report.tex
	@pdflatex $?
	@pdflatex $?
clean:
	@rm -f *.class *.pdf *.log *.aux *.zip
