#!/bin/bash
#
#
# Output in current folder
#
#$ -cwd
#
# Send me an email when job ends or it is aborted
#
#$ -m ea
#
# Specify parallel queue
#$ -q parallel
# and set the number of parallel jobs
#$ -l par_cpu=9

matlab -nodesktop -nosplash -r "fba_pbit_evaluator_real_channel_513"
