#!/bin/bash
#
#
# Output in current folder
#
#$ -cwd
#
# Send me an email when job ends or it is aborted
#
#$ -m ea
#
# Specify parallel queue (put the $ to make it parallel again)
# -q parallel
# and set the number of parallel jobs
# -l par_cpu=8

matlab -nodesktop -nosplash -r "LE_DFE_pbit_evaluator"
